trigger:
  branches:
    include:
      - main
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  RG: "ecowork-rg"
  LOCATION: "eastus"
  ACR_NAME: "ecoworkacr"
  API_IMAGE_NAME: "ecowork-api"
  API_CONTAINER_NAME: "ecoworkapi"
  API_DNS_LABEL: "ecowork-api"

  POSTGRES_HOST: "ecoworkdb.eastus.azurecontainer.io"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "ecoworkdb"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "ecoworkFIAP!"

steps:

# 1. CHECKOUT
- task: Checkout@1
  displayName: "Checkout repository"

# 2. MAVEN BUILD + TEST
- task: Maven@3
  displayName: "Build and Test with Maven"
  inputs:
    mavenPomFile: "pom.xml"
    goals: "clean package"
    options: "-DskipTests=false"
    publishJUnitResults: true
    testResultsFiles: "**/surefire-reports/*.xml"
    javaHomeOption: "JDKVersion"
    jdkVersionOption: "1.17"
    mavenOptions: "-Xmx3072m"

# 3. ACR LOGIN
- task: Docker@2
  displayName: "Login to ACR"
  inputs:
    command: login
    containerRegistry: "$(ACR_SERVICE_CONNECTION)"

# 4. DOCKER BUILD
- task: Docker@2
  displayName: "Build API Docker Image"
  inputs:
    command: build
    repository: "$(ACR_NAME).azurecr.io/$(API_IMAGE_NAME)"
    Dockerfile: "Dockerfile"
    tags: |
      $(Build.BuildId)
      latest

# 5. DOCKER PUSH
- task: Docker@2
  displayName: "Push API Images to ACR"
  inputs:
    command: push
    repository: "$(ACR_NAME).azurecr.io/$(API_IMAGE_NAME)"
    tags: |
      $(Build.BuildId)
      latest

# 6. RUN MIGRATIONS
- task: AzureCLI@2
  displayName: "Run Flyway Migrations"
  inputs:
    azureSubscription: "$(AZURE_SERVICE_CONNECTION)"
    scriptType: bash
    scriptLocation: inlineScript: |

      echo "Running Flyway migrations before deploy..."

      docker run --rm \
        -e POSTGRES_HOST="$(POSTGRES_HOST)" \
        -e POSTGRES_PORT="$(POSTGRES_PORT)" \
        -e POSTGRES_DB="$(POSTGRES_DB)" \
        -e POSTGRES_USER="$(POSTGRES_USER)" \
        -e POSTGRES_PASSWORD="$(POSTGRES_PASSWORD)" \
        "$(ACR_NAME).azurecr.io/$(API_IMAGE_NAME):$(Build.BuildId)" \
        org.flywaydb.core.Flyway migrate

# 7. DEPLOY APP
- task: AzureCLI@2
  displayName: "Deploy API to Container Instance"
  inputs:
    azureSubscription: "$(AZURE_SERVICE_CONNECTION)"
    scriptType: bash
    scriptLocation: inlineScript: |

      echo "Deploying API..."

      az container create \
        --resource-group "$(RG)" \
        --name "$(API_CONTAINER_NAME)" \
        --image "$(ACR_NAME).azurecr.io/$(API_IMAGE_NAME):$(Build.BuildId)" \
        --cpu 1 \
        --memory 1.5 \
        --dns-name-label "$(API_DNS_LABEL)" \
        --ports 8080 \
        --ip-address Public \
        --registry-login-server "$(ACR_NAME).azurecr.io" \
        --registry-username "$(ACR_USERNAME)" \
        --registry-password "$(ACR_PASSWORD)" \
        --environment-variables \
            POSTGRES_HOST="$(POSTGRES_HOST)" \
            POSTGRES_PORT="$(POSTGRES_PORT)" \
            POSTGRES_DB="$(POSTGRES_DB)" \
            POSTGRES_USER="$(POSTGRES_USER)" \
            POSTGRES_PASSWORD="$(POSTGRES_PASSWORD)"
