trigger:
  branches:
    include:
      - master
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  RG: "ecowork-rg"
  LOCATION: "eastus"
  ACR_NAME: "ecoworkacr"
  API_IMAGE_NAME: "ecowork-api"
  API_CONTAINER_NAME: "ecoworkapi"
  API_DNS_LABEL: "ecowork-api"

  MYSQL_DATABASE: "ecoworkdb"
  MYSQL_USER: "ecowork-user"
  MYSQL_PASSWORD: "ecoworkFIAP!"
  MYSQL_ROOT_PASSWORD: "FIAP@2tdspy!"
  MYSQL_CONTAINER_NAME: "ecowork-mysql"

stages:
  - stage: Build
    displayName: 'Build e Testes'
    jobs:
      - job: Build
        steps:
          - checkout: self

          - task: JavaToolInstaller@0
            inputs:
              versionSpec: '17'
              jdkArchitectureOption: 'x64'
              jdkSourceOption: 'PreInstalled'

          - task: Maven@3
            displayName: 'Compilar e Testar'
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean test'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'

  - stage: ContainerImage
    displayName: 'Build da Imagem no ACR'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: BuildContainerImage
        steps:
          - checkout: self
          - task: AzureCLI@2
            displayName: 'Buildar imagem no ACR'
            inputs:
              azureSubscription: '$(azureSubscription)'
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                $ErrorActionPreference = 'Stop'
                $imageTag = "$(Build.BuildId)"
                Write-Host "Buildando imagem $(API_IMAGE_NAME):$imageTag e latest no ACR $(ACR_NAME)..."
                az acr build `
                  --registry "$(ACR_NAME)" `
                  --image "$(API_IMAGE_NAME):$imageTag" `
                  --image "$(API_IMAGE_NAME):latest" `
                  .

  - stage: Deploy
    displayName: 'Deploy'
    dependsOn: ContainerImage
    condition: succeeded()
    jobs:
      - deployment: Deploy
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: AzureCLI@2
                  displayName: 'Criar ou atualizar container group'
                  inputs:
                    azureSubscription: '$(azureSubscription)'
                    scriptType: pscore
                    scriptLocation: inlineScript
                    inlineScript: |
                      $ErrorActionPreference = 'Stop'

                      function Require($value, $name) {
                        if ([string]::IsNullOrWhiteSpace($value)) {
                          Write-Error "Variável $name não definida no pipeline."
                        }
                        return $value
                      }

                      $resourceGroup = "$(RG)"
                      $location = "$(LOCATION)"
                      $containerGroup = "$(API_CONTAINER_NAME)"
                      $acrName = "$(ACR_NAME)"
                      $appImageRepo = "$(API_IMAGE_NAME)"
                      $appContainerName = "$(API_CONTAINER_NAME)"
                      $mysqlContainerName = "$(MYSQL_CONTAINER_NAME)"
                      $mysqlDatabase = "$(MYSQL_DATABASE)"
                      $mysqlUser = "$(MYSQL_USER)"
                      $mysqlPassword = "$(MYSQL_PASSWORD)"
                      $mysqlRootPassword = "$(MYSQL_ROOT_PASSWORD)"
                      $dnsLabel = "$(API_DNS_LABEL)"

                      $loginServer = az acr show --name $acrName --query loginServer -o tsv
                      $imageTag = "$(Build.BuildId)"
                      $appImageFull = "$loginServer/$appImageRepo:$imageTag"
                      $mysqlImageFull = "$loginServer/mysql:latest"

                      # Import MySQL se não existir
                      $tagExists = az acr repository show-tags --name $acrName --repository "mysql" --query "contains(@, 'latest')" -o tsv 2>$null
                      if ($tagExists -ne 'true') {
                        az acr import --name $acrName --source "docker.io/library/mysql:latest" --image "mysql:latest"
                      }

                      # Credenciais ACR
                      $acrUsername = az acr credential show --name $acrName --query username -o tsv
                      $acrPassword = az acr credential show --name $acrName --query passwords[0].value -o tsv

                      # Remover container group existente
                      $exists = az container show --resource-group $resourceGroup --name $containerGroup >$null 2>&1
                      if ($LASTEXITCODE -eq 0) {
                        az container delete --resource-group $resourceGroup --name $containerGroup --yes
                        Write-Host 'Aguardando remoção...'
                        do { Start-Sleep -Seconds 5; az container show --resource-group $resourceGroup --name $containerGroup >$null 2>&1 } while ($LASTEXITCODE -eq 0)
                      }

                      # Configurar containers
                      $springDatasourceUrl = "jdbc:mysql://127.0.0.1:3306/$mysqlDatabase?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"

                      $appContainer = @{ 
                        name = $appContainerName
                        properties = @{ 
                          image = $appImageFull
                          ports = @(@{ port = 8080 })
                          environmentVariables = @(
                            @{ name = 'SERVER_PORT'; value = '8080' },
                            @{ name = 'DB_HOST'; value = '127.0.0.1' },
                            @{ name = 'DB_PORT'; value = '3306' },
                            @{ name = 'SPRING_DATASOURCE_URL'; value = $springDatasourceUrl },
                            @{ name = 'SPRING_DATASOURCE_USERNAME'; value = $mysqlUser },
                            @{ name = 'SPRING_DATASOURCE_PASSWORD'; secureValue = $mysqlPassword },
                            @{ name = 'JAVA_OPTS'; value = '-Xms256m -Xmx512m' }
                          )
                          resources = @{ requests = @{ cpu = 1.0; memoryInGB = 1.5 } }
                        }
                      }

                      $mysqlContainer = @{ 
                        name = $mysqlContainerName
                        properties = @{ 
                          image = $mysqlImageFull
                          ports = @(@{ port = 3306 })
                          environmentVariables = @(
                            @{ name = 'MYSQL_DATABASE'; value = $mysqlDatabase },
                            @{ name = 'MYSQL_USER'; value = $mysqlUser },
                            @{ name = 'MYSQL_PASSWORD'; secureValue = $mysqlPassword },
                            @{ name = 'MYSQL_ROOT_PASSWORD'; secureValue = $mysqlRootPassword },
                            @{ name = 'MYSQL_ROOT_HOST'; value = '%' }
                          )
                          resources = @{ requests = @{ cpu = 1.0; memoryInGB = 1.5 } }
                        }
                      }

                      $templateObject = @{ 
                        name = $containerGroup
                        location = $location
                        properties = @{ 
                          containers = @($appContainer, $mysqlContainer)
                          osType = 'Linux'
                          restartPolicy = 'Always'
                          imageRegistryCredentials = @(@{ server = $loginServer; username = $acrUsername; password = $acrPassword })
                          ipAddress = @{ 
                            type = 'Public'
                            dnsNameLabel = $dnsLabel
                            ports = @(@{ protocol = 'TCP'; port = 8080 }, @{ protocol = 'TCP'; port = 3306 })
                          }
                        }
                      }

                      $templateJson = $templateObject | ConvertTo-Json -Depth 6
                      $tempFile = New-TemporaryFile
                      $templateJson | Out-File -FilePath $tempFile -Encoding utf8
                      try { az container create --resource-group $resourceGroup --file $tempFile | Out-Null }
                      finally { Remove-Item $tempFile -Force }

                      Write-Host "Container group $containerGroup criado com sucesso."
                      Write-Host "Aplicação acessível em: http://$dnsLabel.$location.azurecontainer.io:8080"
